// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // El CLI de Prisma (migrate, db push, etc.) usa la conexión directa,
  // ya que la conexión pooled (DATABASE_URL, pgbouncer) no soporta
  // los comandos de migración de Prisma.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
